//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOnCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public long ID { get; set; }
        public long ClientID { get; set; }
        public string PropertyName { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
