//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOnCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public long ID { get; set; }
        public long PropertyID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string SubscriptionStatus { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
