//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOnCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Status { get; set; }
        public string ConfCode { get; set; }
        public Nullable<int> Confirmed { get; set; }
        public string HashCode { get; set; }
    }
}
